In [1]:
import numpy as np
import pandas as pd

In [2]:
df_ratings  = pd.read_csv('C:/Users/Sunwoo/Desktop/Matrix Factorization/ml-latest-small/ml-latest-small/ratings.csv')
df_movies  = pd.read_csv('C:/Users/Sunwoo/Desktop/Matrix Factorization/ml-latest-small/ml-latest-small/movies.csv')

In [3]:
df_user_movie_ratings = df_ratings.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0)

In [4]:
df_user_movie_ratings.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df_user_movie_ratings['rating_count'] = 0.0
df_user_movie_ratings['rating_count'] = float(9723)-(df_user_movie_ratings.iloc[:,1:] == 0.0).sum(axis=1)

In [6]:
df_user_movie_ratings.head()

movieId,1,2,3,4,5,6,7,8,9,10,...,193567,193571,193573,193579,193581,193583,193585,193587,193609,rating_count
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,230.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,215.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.0

In [7]:
df_user_movie_ratings=df_user_movie_ratings.sort_values(by='rating_count', ascending=False)

In [8]:
df_user_movie_ratings

movieId,1,2,3,4,5,6,7,8,9,10,...,193567,193571,193573,193579,193581,193583,193585,193587,193609,rating_count
userId,,,,,,,,,,,,,,,,,,,,,
414,4.0,3.0,4.0,0.0,2.0,3.0,3.0,3.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2696.0
599,3.0,2.5,1.5,0.0,0.0,4.5,2.5,0.0,1.5,3.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2476.0
474,4.0,3.0,0.0,0.0,1.5,3.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2106.0
448,5.0,3.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1862.0
274,4.0,3.5,0.0,0.0,0.0,4.0,0.0,3.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1344.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
147,0.0,0.0,0.0,0.0,4.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0

In [9]:
df_user_movie_ratings = df_user_movie_ratings.drop(columns = ['rating_count'])

In [10]:
df_user_movie_ratings

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
414,4.0,3.0,4.0,0.0,2.0,3.0,3.0,3.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
599,3.0,2.5,1.5,0.0,0.0,4.5,2.5,0.0,1.5,3.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
474,4.0,3.0,0.0,0.0,1.5,3.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
448,5.0,3.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
274,4.0,3.5,0.0,0.0,0.0,4.0,0.0,3.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
576,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,0.0,0.0,0.0,0.0,4.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
df= None

class MatrixFactorization():
    def __init__(self, R, k, learning_rate, reg_param, epochs, verbose=False):
        """
        :param R: rating matrix
        :param k: latent parameter
        :param learning_rate: alpha on weight update
        :param reg_param: beta on weight update
        :param epochs: training epochs
        :param verbose: print status
        """

        self._R = R
        self._num_users, self._num_items = R.shape
        self._k = k
        self._learning_rate = learning_rate
        self._reg_param = reg_param
        self._epochs = epochs
        self._verbose = verbose


    def fit(self):
        """
        training Matrix Factorization : Update matrix latent weight and bias

        참고: self._b에 대한 설명
        - global bias: input R에서 평가가 매겨진 rating의 평균값을 global bias로 사용
        - 정규화 기능. 최종 rating에 음수가 들어가는 것 대신 latent feature에 음수가 포함되도록 해줌.

        :return: training_process
        """

        # init latent features
        self._P = np.random.normal(size=(self._num_users, self._k))
        self._Q = np.random.normal(size=(self._num_items, self._k))

        # init biases
        self._b_P = np.zeros(self._num_users)
        self._b_Q = np.zeros(self._num_items)
        self._b = np.mean(self._R[np.where(self._R != 0)])

        # train while epochs
        self._training_process = []
        for epoch in range(self._epochs):

            # rating이 존재하는 index를 기준으로 training
            for i in range(self._num_users):
                for j in range(self._num_items):
                    if self._R[i, j] > 0:
                        self.gradient_descent(i, j, self._R[i, j])
            cost = self.cost()
            self._training_process.append((epoch, cost))

            # print status
            if self._verbose == True and ((epoch + 1) % 10 == 0):
                print("Iteration: %d ; cost = %.4f" % (epoch + 1, cost))


    def cost(self):
        """
        compute root mean square error
        :return: rmse cost
        """

        # xi, yi: R[xi, yi]는 nonzero인 value를 의미한다.
        # 참고: http://codepractice.tistory.com/90
        xi, yi = self._R.nonzero()
        predicted = self.get_complete_matrix()
        cost = 0
        for x, y in zip(xi, yi):
            cost += pow(self._R[x, y] - predicted[x, y], 2)
        return np.sqrt(cost) / len(xi)


    def gradient(self, error, i, j):
        """
        gradient of latent feature for GD

        :param error: rating - prediction error
        :param i: user index
        :param j: item index
        :return: gradient of latent feature tuple
        """

        dp = (error * self._Q[j, :]) - (self._reg_param * self._P[i, :])
        dq = (error * self._P[i, :]) - (self._reg_param * self._Q[j, :])
        return dp, dq


    def gradient_descent(self, i, j, rating):
        """
        graident descent function

        :param i: user index of matrix
        :param j: item index of matrix
        :param rating: rating of (i,j)
        """

        # get error
        prediction = self.get_prediction(i, j)
        error = rating - prediction

        # update biases
        self._b_P[i] += self._learning_rate * (error - self._reg_param * self._b_P[i])
        self._b_Q[j] += self._learning_rate * (error - self._reg_param * self._b_Q[j])

        # update latent feature
        dp, dq = self.gradient(error, i, j)
        self._P[i, :] += self._learning_rate * dp
        self._Q[j, :] += self._learning_rate * dq


    def get_prediction(self, i, j):
        """
        get predicted rating: user_i, item_j
        :return: prediction of r_ij
        """
        return self._b + self._b_P[i] + self._b_Q[j] + self._P[i, :].dot(self._Q[j, :].T)


    def get_complete_matrix(self):
        """
        computer complete matrix PXQ + P.bias + Q.bias + global bias

        - PXQ 행렬에 b_P[:, np.newaxis]를 더하는 것은 각 열마다 bias를 더해주는 것
        - b_Q[np.newaxis:, ]를 더하는 것은 각 행마다 bias를 더해주는 것
        - b를 더하는 것은 각 element마다 bias를 더해주는 것

        - newaxis: 차원을 추가해줌. 1차원인 Latent들로 2차원의 R에 행/열 단위 연산을 해주기위해 차원을 추가하는 것.

        :return: complete matrix R^
        """
        return self._b + self._b_P[:, np.newaxis] + self._b_Q[np.newaxis:, ] + self._P.dot(self._Q.T)
    
    def to_dataframe(self):
        #matrix를 csv파일로 내보내기위해 dataframe으로 변환
        global df
        df=pd.DataFrame(self.get_complete_matrix(), columns = df_user_movie_ratings.columns, index = df_user_movie_ratings.index)
        
        return df

    def print_results(self):
        """
        print fit results
        """

        #print("User Latent P:")
        #print(self._P)
        #print("Item Latent Q:")
        #print(self._Q.T)
        #print("P x Q:")
        #print(self._P.dot(self._Q.T))
        #print("bias:")
        #print(self._b)
        #print("User Latent bias:")
        #print(self._b_P)
        #print("Item Latent bias:")
        #print(self._b_Q)
        print("Final R matrix:")
        print(self.get_complete_matrix())
        
        #np.savetxt("result.txt",self.get_complete_matrix())
        print("Final RMSE:")
        print(self._training_process[self._epochs-1][1])

In [12]:
# run example
if __name__ == "__main__":
    # rating matrix - User X Item : (7 X 5)
    '''R = np.array([
        [1, 0, 0, 1, 3],
        [2, 0, 3, 1, 1],
        [1, 2, 0, 5, 0],
        [1, 0, 0, 4, 4],
        [2, 1, 5, 4, 0],
        [5, 1, 5, 4, 0],
        [0, 0, 0, 1, 0],
    ])'''
    
    R=df_user_movie_ratings.values

    # P, Q is (7 X k), (k X 5) matrix
    factorizer = MatrixFactorization(R, k=30, learning_rate=0.01, reg_param=0.01, epochs=1000, verbose=True)
    factorizer.fit()
    factorizer.print_results()
    factorizer.to_dataframe()

Iteration: 10 ; cost = 0.0024
Iteration: 20 ; cost = 0.0023
Iteration: 30 ; cost = 0.0022
Iteration: 40 ; cost = 0.0021
Iteration: 50 ; cost = 0.0020
Iteration: 60 ; cost = 0.0020
Iteration: 70 ; cost = 0.0019
Iteration: 80 ; cost = 0.0018
Iteration: 90 ; cost = 0.0018
Iteration: 100 ; cost = 0.0017
Iteration: 110 ; cost = 0.0017
Iteration: 120 ; cost = 0.0016
Iteration: 130 ; cost = 0.0016
Iteration: 140 ; cost = 0.0015
Iteration: 150 ; cost = 0.0015
Iteration: 160 ; cost = 0.0015
Iteration: 170 ; cost = 0.0014
Iteration: 180 ; cost = 0.0014
Iteration: 190 ; cost = 0.0014
Iteration: 200 ; cost = 0.0013
Iteration: 210 ; cost = 0.0013
Iteration: 220 ; cost = 0.0013
Iteration: 230 ; cost = 0.0013
Iteration: 240 ; cost = 0.0012
Iteration: 250 ; cost = 0.0012
Iteration: 260 ; cost = 0.0012
Iteration: 270 ; cost = 0.0012
Iteration: 280 ; cost = 0.0012
Iteration: 290 ; cost = 0.0012
Iteration: 300 ; cost = 0.0011
Iteration: 310 ; cost = 0.0011
Iteration: 320 ; cost = 0.0011
Iteration: 330 ; cost = 0.0011
Iteration: 340 ; cost = 0.0011
Iteration: 350 ; cost = 0.0011
Iteration: 360 ; cost = 0.0011
Iteration: 370 ; cost = 0.0011
Iteration: 380 ; cost = 0.0010
Iteration: 390 ; cost = 0.0010
Iteration: 400 ; cost = 0.0010
Iteration: 410 ; cost = 0.0010
Iteration: 420 ; cost = 0.0010
Iteration: 430 ; cost = 0.0010
Iteration: 440 ; cost = 0.0010
Iteration: 450 ; cost = 0.0010
Iteration: 460 ; cost = 0.0010
Iteration: 470 ; cost = 0.0010
Iteration: 480 ; cost = 0.0010
Iteration: 490 ; cost = 0.0009
Iteration: 500 ; cost = 0.0009
Iteration: 510 ; cost = 0.0009
Iteration: 520 ; cost = 0.0009
Iteration: 530 ; cost = 0.0009
Iteration: 540 ; cost = 0.0009
Iteration: 550 ; cost = 0.0009
Iteration: 560 ; cost = 0.0009
Iteration: 570 ; cost = 0.0009
Iteration: 580 ; cost = 0.0009
Iteration: 590 ; cost = 0.0009
Iteration: 600 ; cost = 0.0009
Iteration: 610 ; cost = 0.0009
Iteration: 620 ; cost = 0.0009
Iteration: 630 ; cost = 0.0009
Iteration: 640 ; cost = 0.0009
Iteration: 650 ; cost = 0.0008
Iteration: 660 ; cost = 0.0008
Iteration: 670 ; cost = 0.0008
Iteration: 680 ; cost = 0.0008
Iteration: 690 ; cost = 0.0008
Iteration: 700 ; cost = 0.0008
Iteration: 710 ; cost = 0.0008
Iteration: 720 ; cost = 0.0008
Iteration: 730 ; cost = 0.0008
Iteration: 740 ; cost = 0.0008
Iteration: 750 ; cost = 0.0008
Iteration: 760 ; cost = 0.0008
Iteration: 770 ; cost = 0.0008
Iteration: 780 ; cost = 0.0008
Iteration: 790 ; cost = 0.0008
Iteration: 800 ; cost = 0.0008
Iteration: 810 ; cost = 0.0008
Iteration: 820 ; cost = 0.0008
Iteration: 830 ; cost = 0.0008
Iteration: 840 ; cost = 0.0008
Iteration: 850 ; cost = 0.0008
Iteration: 860 ; cost = 0.0008
Iteration: 870 ; cost = 0.0008
Iteration: 880 ; cost = 0.0008
Iteration: 890 ; cost = 0.0008
Iteration: 900 ; cost = 0.0008
Iteration: 910 ; cost = 0.0008
Iteration: 920 ; cost = 0.0008
Iteration: 930 ; cost = 0.0008
Iteration: 940 ; cost = 0.0008
Iteration: 950 ; cost = 0.0008
Iteration: 960 ; cost = 0.0008
Iteration: 970 ; cost = 0.0008
Iteration: 980 ; cost = 0.0008
Iteration: 990 ; cost = 0.0008
Iteration: 1000 ; cost = 0.0008
Final R matrix:
[[3.67836458 3.70132725 3.53518358 ... 4.61560999 1.57573818 4.95078024]
 [3.17488614 2.56438823 1.65666279 ... 3.29067304 1.72710438 2.79877411]
 [3.46294783 3.1024533  3.37504217 ... 4.18715975 3.05972114 5.30691469]
 ...
 [3.84135051 3.98002079 2.91296191 ... 2.94530639 2.6667752  3.7652868 ]
 [3.98710097 3.89910263 2.88490432 ... 3.04446388 1.15772963 3.05135247]
 [3.16907842 3.74915312 2.97224153 ... 3.79440394 4.79742217 4.6622597 ]]
Final RMSE:
0.0007667279972592768

In [14]:
#print(df)
#df_user_movie_ratings.to_csv('C:/Users/Sunwoo/Desktop/Matrix Factorization/result/result0.csv')
df.to_csv('C:/Users/Sunwoo/Desktop/Matrix Factorization/result/result_sortby.csv')